/* ################################ AUTH ####################### */
export const LOGIN = 'LOGIN'
export const LOGIN_RECEIVED = 'LOGIN_RECEIVED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_RECEIVED = 'LOGOUT_RECEIVED'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const REGISTER = 'REGISTER'
export const REGISTER_RECEIVED = 'REGISTER_RECEIVED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const CLEAR_REGISTER = 'CLEAR_REGISTER'


/* ################################ FIN AUTH ####################### */

/* ################## QUEST ################## */

export const CREATE_QUESTIONNARIES = 'CREATE_QUESTIONNARIES'
export const CREATE_QUESTIONNARIES_RECEIVED = 'CREATE_QUESTIONNARIES_RECEIVED'
export const CREATE_QUESTIONNARIES_FAILED = 'CREATE_QUESTIONNARIES_FAILED'

export const GET_QUESTIONNARIES = 'GET_QUESTIONNARIES'
export const GET_QUESTIONNARIES_RECEIVED = 'GET_QUESTIONNARIES_RECEIVED'
export const GET_QUESTIONNARIES_FAILED = 'GET_QUESTIONNARIES_FAILED'

export const CLEAR_QUESTIONNARIES = 'CLEAR_QUESTIONNARIES'

export const DELETE_QUESTIONNARIES = 'DELETE_QUESTIONNARIES'
export const DELETE_QUESTIONNARIES_RECEIVED = 'DELETE_QUESTIONNARIES_RECEIVED'
export const DELETE_QUESTIONNARIES_FAILED = 'DELETE_QUESTIONNARIES_FAILED'

export const CLEAR_DEL_QUEST = 'CLEAR_DEL_QUEST'

export const GET_BY_ID_QUESTIONNARIES = 'GET_BY_ID_QUESTIONNARIES'
export const GET_BY_ID_QUESTIONNARIES_RECEIVED = 'GET_BY_ID_QUESTIONNARIES_RECEIVED'
export const GET_BY_ID_QUESTIONNARIES_FAILED = 'GET_BY_ID_QUESTIONNARIES_FAILED'

export const UPDATE_QUESTIONNARIES = 'UPDATE_QUESTIONNARIES'
export const UPDATE_QUESTIONNARIES_RECEIVED = 'UPDATE_QUESTIONNARIES_RECEIVED'
export const UPDATE_QUESTIONNARIES_FAILED = 'UPDATE_QUESTIONNARIES_FAILED'


/* ################## END QUEST ################## */